# Generated by Django 3.2.5 on 2021-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='places',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
