# Generated by Django 3.2.5 on 2021-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_details_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='places',
            field=models.CharField(max_length=1000),
        ),
    ]
