# Generated by Django 3.2.5 on 2021-08-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_details_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='places',
        ),
    ]
