# Generated by Django 3.2.5 on 2021-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_remove_details_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='places',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
